### PR TITLE
Code snippets

### PR DESCRIPTION
**Pull request by batracos**
Added snippets for `If`, `Which`, `Switch`, `Module` and new function template.

### CODE REVIEW

**Comment by shigma** [comment]
If you provided a `Module` snippet, why not consider `DynamicModule`, `Block` and `With`?

**Comment by batracos** [comment]
This was just a few experiments I put here to get the ball rolling.
Besides the ones you mentioned, which functions do you think we should add?

If the answer is "all", then we should look into a build script that scrape the documentation usage messages, but then I don't know what's the deal with the licensing and I will have to ask.

**Comment by chere005** [comment]
I agree DynamicModule/Block/With are obvious and common to come with Module.. Perhaps at some point we could do some scraping but I think there's only a handful of snippets that are going to be used very often.. 

That said I tried these a while ago and it's really not how I indent my code. I haven't had time to revisit how I would do these, but I have a feeling we're going to disagree and I'm not sure how to resolve that. At some point people will probably tweak their local config slightly I'm sure. I would prefer more minimal snippits that look like this (I also don't like the comments being added as placeholders since they're not easy to double click.. a camel cased word would be better):

```
If[(* cursor here *),

	,

]

Module[
	{
		(* cursor here *)
	},

	
]


Switch[(* cursor here *),
	patt1,

	,
	_,
	
]

Which[
	(* cursor here *),
	value1

	,
	True, 
	
]
```

I found the new function bit completely overkill.. Perhaps I'll come up with what mine would look like soon. If you like any of these changes I can move on to modifying the snippit files

**Comment by chere005** [comment]
Ah, I didn't notice the tab behavior.. I'm not sure if I like it yet. I'm going to try to use it today

**Comment by batracos** [comment]
One thing that annoys me is that the snippets for `Module`, `DynamicModule`, `Block` and `With` are basically the same but I don't think we can have multiple triggers for the same snippet with a variable head.

We could have a *scope* snippet that has the head as the first parameter but I don't think it would be as useful.

**Pull request closed without merging**
